### ISSUE TITLE
问个关于原始项目的问题

### ISSUE THREAD

**Issue by lueyoung** [ZhenYongFan/libRaft#1]
你号，麻烦我想问下，原始项目的话，您能给个uescase嘛，谢谢了。看了几天代码，不知道怎么去搭建一个Raft网络，如果有相关资料，麻烦提供一下，多谢！

**Comment by ZhenYongFan** [comment]
你是想构建真正的网络服务吧，请参考libraftext这个工程，我的目标是core只是核心算法，在ext封装网络和具体的kv服务和分布式锁服务（还没有提交呢）

**Comment by lueyoung** [comment]
好的，谢谢！期待你继续更新！
